language: go
sudo: required
dist: trusty

go:
  - master # This uses automatically the latest version of go

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
script:
  - hugo # This commands builds your website on travis

deploy:
  provider: firebase
  token:
    secure: TeyLU7h9EzKMZj1Gb3yWgrkAqX3qyKPkv4OKNvI9yOhjgTL0pVgpqULlKuWaaK3zycajva8pEaBcvmfQPE9WO0Nq1cbVJOgkVuVRdlUupGuSW1PzHAm3SXXAwAZpSqkGX++7t8tMdM9wAIxzShX/471wdkZVjglOol72eUYhgOTcPiM5vDYz1gksDUdTS1yvFcpKgcHEYHmPs5y6j0/42qsI/zJu+sdXcL0+sXX4Mpljfi1Hs/YJZO0nYfULGKBwsS01P6RHgTBNTumlEiJDYd5EB1rCJB7+pLJyk7z5cLyYmNDKEb37zXpDHM5W87NAMeH5SNlo5JXxqo/A2R2XbbfpDuN6jYqCzy3ojJWDRvQovRnXlHWk8LoIYr6VX/az1CHPSQfv5Wc5sEF/Xh2i/K62uaI8EWhbJhUatLbPm25lV4qnefEnGAiIn72WhEOyFjzuBv8AdlHKZ92e/7Bfoiamg3gox7O0iaDfjZNAtCFudRX7PkNXTmoXdbXvtPuvFOo+UBR+xhKIj0EgPudIK7QYMgeqMxMwwF+c3jKbWMWW44XEhM5PHGfXwEIgJCluO7q6MwVXW+E9K+6bjgRsti/8tT/Bcz451Gnu02Dg17gKHzp2y+gpj1E//LNHVkWnbJNfdfAtqZ3eMacuRAtVRWuNV/E7Hnxo67kw/B96EaI=
  skip_cleanup: true
  on:
    branch: master
